"""Click address map for the big jig flipper.

X101-X109 proxes. X109 is the jig-fully-placed switch, wired to the PLC.
Robot commands are the EtherNet/IP words.
DS1-DS4 to the scanner: ready, place error, at A, at B.
DS5 flip to A, DS6 flip to B, DS8 error ack, from the scanner. DS7 is spare.
DS9-DS20 from the scanner are the pendant jog commands. DS20 links both lifts.
Y206-Y216 outputs on the bottom of the Y2 module.
AllowJigSense is Y206; each following valve is the next address.
C1-C14 sequencer. C15 place error. C104 error ack.
C101/C102 robot flip requests, copied from DS5 and DS6.
C20 E-stop. C32 holds that E-stop until the robot requests drop.
C21 jog mode. C22-C31 jog pushes, copied from DS9-DS19. DS20 links those lifts.
T1-T5 / TD1-TD5 settle timers (1 s).
T6 / TD6 jig-placed timeout (40 s).

Analog clamp (voltage linear sensor) is not mapped yet. When it lands, use a
DF register for the raw volts and compare in calc() rungs. Do not reuse these
X/Y/C addresses.
"""

from pyrung.click import ClickBlocks, TagMap

from machines.big_jig_flipper.logic import (
    AfterClamp1,
    AfterClamp2,
    AfterDown,
    AfterLift,
    AfterRotate,
    AProx,
    AStartCheck,
    AllowJigSense,
    BProx,
    BStartCheck,
    Clamp1Valve,
    Clamp2Valve,
    ClampedProx1,
    ClampedProx2,
    ErrorAck,
    Estop,
    EstopHold,
    FlipDirection,
    FlipToA,
    FlipToARbt,
    FlipToB,
    FlipToBRbt,
    Holding,
    JigPlaced,
    JogClamp1In,
    JogClamp1Out,
    JogClamp2In,
    JogClamp2Out,
    JogLift1Dn,
    JogLift1Up,
    JogLift2Dn,
    JogLift2Up,
    JogMode,
    JogRotateA,
    JogRotateB,
    Lift1,
    Lift1DnValve,
    Lift1UpValve,
    Lift2,
    Lift2DnValve,
    Lift2UpValve,
    LiftUpProx1,
    LiftUpProx2,
    PlaceError,
    PlaceTimeout,
    ResetToHold,
    RobotAtA,
    RobotAtB,
    RobotError,
    RobotErrorAck,
    RobotFlipA,
    RobotFlipB,
    RobotJogClamp1In,
    RobotJogClamp1Out,
    RobotJogClamp2In,
    RobotJogClamp2Out,
    RobotJogLift1Dn,
    RobotJogLift1Up,
    RobotJogLift2Dn,
    RobotJogLift2Up,
    RobotJogLink,
    RobotJogMode,
    RobotJogRotateA,
    RobotJogRotateB,
    RobotReady,
    RotateToAValve,
    RotateToBValve,
    SetDown,
    SlideClampsIn1,
    SlideClampsIn2,
    SlideClampsOut1,
    SlideClampsOut2,
    Unclamp1Valve,
    Unclamp2Valve,
    UnclampedProx1,
    UnclampedProx2,
)

blocks = ClickBlocks()

mapping = TagMap(
    {
        AProx: blocks.x[101],
        BProx: blocks.x[102],
        ClampedProx1: blocks.x[103],
        ClampedProx2: blocks.x[104],
        UnclampedProx1: blocks.x[105],
        UnclampedProx2: blocks.x[106],
        LiftUpProx1: blocks.x[107],
        LiftUpProx2: blocks.x[108],
        JigPlaced: blocks.x[109],
        RobotReady: blocks.ds[1],
        RobotError: blocks.ds[2],
        RobotAtA: blocks.ds[3],
        RobotAtB: blocks.ds[4],
        RobotFlipA: blocks.ds[5],
        RobotFlipB: blocks.ds[6],
        RobotErrorAck: blocks.ds[8],
        RobotJogMode: blocks.ds[9],
        RobotJogLift1Up: blocks.ds[10],
        RobotJogLift1Dn: blocks.ds[11],
        RobotJogLift2Up: blocks.ds[12],
        RobotJogLift2Dn: blocks.ds[13],
        RobotJogClamp1In: blocks.ds[14],
        RobotJogClamp1Out: blocks.ds[15],
        RobotJogClamp2In: blocks.ds[16],
        RobotJogClamp2Out: blocks.ds[17],
        RobotJogRotateA: blocks.ds[18],
        RobotJogRotateB: blocks.ds[19],
        RobotJogLink: blocks.ds[20],
        AllowJigSense: blocks.y[206],
        Lift1UpValve: blocks.y[207],
        Lift1DnValve: blocks.y[208],
        Lift2UpValve: blocks.y[209],
        Lift2DnValve: blocks.y[210],
        Clamp1Valve: blocks.y[211],
        Unclamp1Valve: blocks.y[212],
        Clamp2Valve: blocks.y[213],
        Unclamp2Valve: blocks.y[214],
        RotateToAValve: blocks.y[215],
        RotateToBValve: blocks.y[216],
        Holding: blocks.c[1],
        AStartCheck: blocks.c[2],
        BStartCheck: blocks.c[3],
        SlideClampsIn1: blocks.c[4],
        SlideClampsIn2: blocks.c[5],
        Lift1: blocks.c[6],
        Lift2: blocks.c[7],
        FlipDirection: blocks.c[8],
        FlipToA: blocks.c[9],
        FlipToB: blocks.c[10],
        SetDown: blocks.c[11],
        SlideClampsOut1: blocks.c[12],
        SlideClampsOut2: blocks.c[13],
        ResetToHold: blocks.c[14],
        PlaceError: blocks.c[15],
        FlipToARbt: blocks.c[101],
        FlipToBRbt: blocks.c[102],
        ErrorAck: blocks.c[104],
        Estop: blocks.c[20],
        EstopHold: blocks.c[32],
        JogMode: blocks.c[21],
        JogLift1Up: blocks.c[22],
        JogLift1Dn: blocks.c[23],
        JogLift2Up: blocks.c[24],
        JogLift2Dn: blocks.c[25],
        JogClamp1In: blocks.c[26],
        JogClamp1Out: blocks.c[27],
        JogClamp2In: blocks.c[28],
        JogClamp2Out: blocks.c[29],
        JogRotateA: blocks.c[30],
        JogRotateB: blocks.c[31],
        AfterClamp1.Done: blocks.t[1],
        AfterClamp1.Acc: blocks.td[1],
        AfterClamp2.Done: blocks.t[2],
        AfterClamp2.Acc: blocks.td[2],
        AfterLift.Done: blocks.t[3],
        AfterLift.Acc: blocks.td[3],
        AfterRotate.Done: blocks.t[4],
        AfterRotate.Acc: blocks.td[4],
        AfterDown.Done: blocks.t[5],
        AfterDown.Acc: blocks.td[5],
        PlaceTimeout.Done: blocks.t[6],
        PlaceTimeout.Acc: blocks.td[6],
    }
)
